import React from 'react';
import { APP_WIDTH } from './utils';

export const s: Record<string, React.CSSProperties> = {
  page: {
    minHeight: '100vh',
    backgroundColor: '#F3F4F6',
    fontFamily: 'Inter, sans-serif',
  },
  shell: {
    width: '100%',
    maxWidth: `${APP_WIDTH}px`,
    margin: '0 auto',
    minHeight: '100vh',
    backgroundColor: '#F8FAFC',
    position: 'relative',
    overflowX: 'hidden',
  },
  app: {
    minHeight: '100vh',
    paddingBottom: '120px',
  },
  header: {
    padding: '40px 25px 20px',
  },
  card: {
    backgroundColor: 'white',
    padding: '24px',
    borderRadius: '32px',
    boxShadow: '0 8px 24px rgba(0,0,0,0.04)',
    marginBottom: '16px',
  },
  darkCard: {
    backgroundColor: '#1E293B',
    color: 'white',
    padding: '30px 20px',
    borderRadius: '35px',
    textAlign: 'center',
    marginBottom: '25px',
  },
  input: {
    width: '100%',
    padding: '14px',
    borderRadius: '16px',
    border: '1.5px solid #F1F5F9',
    marginBottom: '10px',
    boxSizing: 'border-box',
    fontSize: '15px',
    outline: 'none',
    backgroundColor: 'white',
  },
  labelIcon: {
    display: 'flex',
    alignItems: 'center',
    gap: '5px',
    fontSize: '10px',
    color: '#94A3B8',
    fontWeight: '800',
    marginBottom: '8px',
    textTransform: 'uppercase',
  },
  btn: {
    width: '100%',
    padding: '18px',
    borderRadius: '24px',
    border: 'none',
    color: 'white',
    fontWeight: '700',
    cursor: 'pointer',
    fontSize: '16px',
  },
  btnPrimary: {
    width: '100%',
    padding: '18px',
    borderRadius: '24px',
    border: 'none',
    color: 'white',
    fontWeight: '700',
    cursor: 'pointer',
    fontSize: '16px',
    backgroundColor: '#5DB386',
    marginTop: '10px',
  },
  toggleW: {
    display: 'flex',
    gap: '8px',
    marginBottom: '20px',
    backgroundColor: '#F1F5F9',
    padding: '6px',
    borderRadius: '18px',
  },
  toggleB: {
    flex: 1,
    padding: '12px',
    borderRadius: '14px',
    border: 'none',
    fontWeight: '700',
    cursor: 'pointer',
    fontSize: '13px',
    background: 'transparent',
  },
  navWrap: {
    position: 'fixed',
    bottom: 20,
    left: '50%',
    transform: 'translateX(-50%)',
    width: '100%',
    maxWidth: `${APP_WIDTH}px`,
    padding: '0 20px',
    boxSizing: 'border-box',
    pointerEvents: 'none',
  },
  nav: {
    height: '75px',
    backgroundColor: 'white',
    display: 'flex',
    justifyContent: 'space-around',
    alignItems: 'center',
    boxShadow: '0 10px 30px rgba(0,0,0,0.08)',
    borderRadius: '40px',
    pointerEvents: 'auto',
  },
  navButton: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    width: '48px',
    height: '48px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '14px',
  },
};
